Repository LT-Students/DigitalOffice-AuthService, pull requests merged in 2021-07, with the labels that each got.

#22 Add refresh token
  src/AuthService.Broker/Consumers/CheckTokenConsumer.cs
  src/AuthService.Broker/Consumers/GetTokenConsumer.cs
  src/AuthService.Business/Commands/Interfaces/IRefreshTokenCommand.cs
  src/AuthService.Business/Commands/LoginCommand.cs
  src/AuthService.Business/Commands/RefreshTokenCommand.cs
  src/AuthService.Models.Dto/Enums/TokenType.cs
  src/AuthService.Models.Dto/Requests/RefreshRequest.cs
  src/AuthService.Models.Dto/Responses/LoginResult.cs
  src/AuthService.Token/AuthService.Token.csproj
  src/AuthService.Token/Interfaces/ITokenEngine.cs
  src/AuthService.Token/Interfaces/ITokenValidator.cs
  src/AuthService.Token/TokenEngine.cs
  src/AuthService.Token/TokenSettings.cs
  src/AuthService.Token/TokenValidator.cs
  src/AuthService.Validation/Interfaces/IRefreshValidator.cs
  src/AuthService.Validation/RefreshValidator.cs
  src/AuthService/Controllers/AuthController.cs
  src/AuthService/appsettings.Development.json
  src/AuthService/appsettings.Production.json
  test/AuthService.Broker.UnitTests/Consumers/UserJwtConsumerTests.cs
  test/AuthService.Token.UnitTests/CreateNewTokenTests.cs
  test/AuthService.Token.UnitTests/JwtValidationTests.cs
Labels: enhancement

#23 fix specification
  src/AuthService/Startup.cs
Labels: bug

#26 fix github actions
  .github/workflows/main.yml
Labels: documentation

#24 Add token lifetime
  Common.Configurations.targets
  src/AuthService.Broker/Consumers/GetTokenConsumer.cs
  src/AuthService.Business/Commands/LoginCommand.cs
  src/AuthService.Business/Commands/RefreshTokenCommand.cs
  src/AuthService.Models.Dto/Responses/LoginResult.cs
  src/AuthService.Token/Interfaces/ITokenEngine.cs
  src/AuthService.Token/TokenEngine.cs
  test/AuthService.Token.UnitTests/CreateNewTokenTests.cs
Labels: enhancement

#28 fix token expires in time
  src/AuthService.Token/TokenEngine.cs
Labels: bug

#29 fix Production settings
  src/AuthService/appsettings.Production.json
Labels: bug

#30 docs/change_actions
  .github/workflows/main.yml
Labels: documentation
